service: server-name-generator

provider:
    name: aws
    runtime: nodejs14.x
    environment:
        IS_SERVERLESS: true
    apiGateway:
        shouldStartNameWithService: true

plugins:
    - serverless-offline

custom:
    serverless-offline:
        httpPort: 4000

functions:
    api:
        handler: src/index.default
        events:
            - http: GET /
            - http: GET /{proxy+}
