const marvel = [
    "Ant-Man",
    "Arnim Zola",
    "Baron Zemo",
    "Beast",
    "Black Panther",
    "Black Widow",
    "Blob",
    "Captain America",
    "Captain Marvel",
    "Colossus",
    "Cyclops",
    "Daredevil",
    "Deadpool",
    "Doctor Octopus",
    "Domino",
    "Dr. Strange",
    "Drax",
    "Elektra",
    "Falcon",
    "Fenris",
    "Gambit",
    "Gamora",
    "Groot",
    "Gwen Stacy",
    "Hank Pym",
    "Havok",
    "Hawkeye",
    "Hela",
    "Hulk",
    "Hydra",
    "Iceman",
    "Iron Fist",
    "Iron Man",
    "Jane Foster",
    "Jarvis",
    "Jessica Jones",
    "Johnny Storm",
    "Juggernaut",
    "Kingpin",
    "Kitty Pride",
    "Korg",
    "Loki",
    "Luke Cage",
    "Magneto",
    "Mantis",
    "Mephisto",
    "Moon Knight",
    "Morbius",
    "Ms. Marvel",
    "Mystique",
    "Nebula",
    "Nick Fury",
    "Nightcrawler",
    "Nighthawk",
    "Odin",
    "Professor X",
    "Punisher",
    "Quicksilver",
    "Red Skull",
    "Rogue",
    "Sabretooth",
    "Sabretooth",
    "Sandman",
    "Scarlet Witch",
    "Shang-Chi",
    "She-Hulk",
    "Sif",
    "Silver Surfer",
    "Spiderman",
    "Starlord",
    "Storm",
    "Thanos",
    "Thing",
    "Thor",
    "Toad",
    "Ultron",
    "Valkyrie",
    "Wanda Maximoff",
    "Wasp",
    "Whiplash",
    "Winter Soldier",
];

const starTrek = [
    "Archer",
    "Bashir",
    "Beverly",
    "Bones",
    "Belanna",
    "Boothby",
    "Chakotay",
    "Chekov",
    "Computer",
    "Crusher",
    "Curzon",
    "Data",
    "Dax",
    "Doctor",
    "Dukat",
    "Garak",
    "Gowron",
    "Harry Kim",
    "Hoshi",
    "Jadzia",
    "Janeway",
    "Jean-Luc",
    "Khan",
    "Kira Nerys",
    "Kirk",
    "Kobayashi Maru",
    "La Forge",
    "Lore",
    "Mayweather",
    "McCoy",
    "Neelix",
    "OBrien",
    "Odo",
    "Phlox",
    "Picard",
    "Q",
    "Quark",
    "Reed",
    "Riker",
    "Sarek",
    "Sato",
    "Scotty",
    "Seven of Nine",
    "Sisko",
    "Spock",
    "Sulu",
    "Tasha",
    "Tom Paris",
    "Torres",
    "TPol",
    "Trip Tucker",
    "Troi",
    "Tuvok",
    "Uhura",
    "Wesley",
    "Worf",
];
const gameOfThrones = [
    "Arya",
    "Baelish",
    "Baratheon",
    "Bolton",
    "Bran",
    "Brienne",
    "Bronn",
    "Cersei",
    "Clegane",
    "Daenerys",
    "Gendry",
    "Greyjoy",
    "Hodor",
    "Jaime",
    "Joffrey",
    "Jon Snow",
    "Khal Drogo",
    "Margaery",
    "Melisandre",
    "Ned Stark",
    "Sansa",
    "Ser Davos",
    "Ser Jorah",
    "Stannis",
    "Stark",
    "Tarly",
    "Theon",
    "Tommen",
    "Tyrion",
    "Tywin",
    "Varys",
    "Viserys",
    "Yara",
    "Ygritte",
];

module.exports = { marvel, starTrek, gameOfThrones };
